#14: Update regression test result upload (#15)
* #14: Upgrade dependencies

* Update references

* Fix / exclude vulnerabilities

* Fix compiler warnings

* Fix running tests on remote docker host

* Reduce log level

* #14: Update regression test result upload

* Add instructions for creating google key

* Run smoketests before regression tests

* Fix failing regression tests

java.lang.NoClassDefFoundError: com/exasol/performancetestrecorder/PerformanceTestRecorder